apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: modelforge
  labels:
    app.kubernetes.io/name: modelforge
    app.kubernetes.io/component: minio
type: Opaque
stringData:
  MINIO_ROOT_USER: "modelforgeadmin"
  MINIO_ROOT_PASSWORD: "ModelForgeMinioSecret2026!"
